using System;
using System.Collections.Generic;
using UnityEngine;

namespace RecastCustomizer
{
    /// <summary>
    /// Inspector-authored source of truth for the modular glove: which segments exist,
    /// which child renderer each one drives, and the ordered material variants that can
    /// be swapped onto it. Mirrors glove_manifest.json, but with direct asset references
    /// so nothing depends on runtime string lookups.
    ///
    /// Populate it by hand, or via  Recast Customizer ▸ Rebuild Variant Set From Folder.
    /// </summary>
    [CreateAssetMenu(menuName = "Recast Customizer/Glove Variant Set", fileName = "falcon_glove_variant_set")]
    public class GloveVariantSet : ScriptableObject
    {
        [Serializable]
        public class Segment
        {
            [Tooltip("Stable id, e.g. \"top\". Also used as the UI label if Label is blank.")]
            public string id;

            [Tooltip("Human-readable label shown in the customizer UI.")]
            public string label;

            [Tooltip("Name of the child GameObject/Renderer under the assembly root this segment controls.")]
            public string childRenderer;

            [Tooltip("Ordered variants. Index 0 is the default. Variant ids are parallel to this list.")]
            public List<Material> variants = new();

            [Tooltip("Parallel to Variants: the id string for each entry, e.g. \"01\". Used in filenames/codes.")]
            public List<string> variantIds = new();

            [Tooltip("Parallel to Variants: the name shown in the customizer UI, e.g. \"Imperial Gold\". " +
                     "Leave an entry blank to fall back to its variant id.")]
            public List<string> variantLabels = new();

            [Tooltip("Parallel to Variants: baked preview images showing the variant on this " +
                     "segment's real geometry. Generated by " +
                     "Recast Customizer > Bake Variant Thumbnails. " +
                     "Where an entry is missing the UI falls back to the material's base map.")]
            public List<Texture2D> variantThumbnails = new();

            [Tooltip("Parallel to Variants: what each variant contributes to the glove's " +
                     "attributes. Seed them from the materials with " +
                     "Recast Customizer > Seed Attributes From Materials, then hand-tune " +
                     "to taste — these are design values, not measurements.")]
            public List<VariantStats> variantStats = new();

            /// <summary>A variant's contribution to one attribute, 0 when unauthored.</summary>
            public float Stat(int variant, int attribute)
            {
                if (variantStats == null || variant < 0 || variant >= variantStats.Count) return 0f;
                var s = variantStats[variant];
                if (s == null || s.values == null || attribute < 0 || attribute >= s.values.Count) return 0f;
                return s.values[attribute];
            }

            public string DisplayLabel => string.IsNullOrEmpty(label) ? id : label;

            public int VariantCount => variants?.Count ?? 0;

            public string VariantId(int index) =>
                (variantIds != null && index >= 0 && index < variantIds.Count)
                    ? variantIds[index]
                    : index.ToString("00");

            /// <summary>Material for a variant, or null when the index is out of range.</summary>
            public Material VariantMaterial(int index) =>
                (variants != null && index >= 0 && index < variants.Count)
                    ? variants[index]
                    : null;

            /// <summary>
            /// Baked preview for a variant, or null if none has been generated yet.
            /// Callers should fall back to the material's base map.
            /// </summary>
            public Texture2D VariantThumbnail(int index) =>
                (variantThumbnails != null && index >= 0 && index < variantThumbnails.Count)
                    ? variantThumbnails[index]
                    : null;

            /// <summary>UI-facing name for a variant; falls back to its id when unnamed.</summary>
            public string VariantLabel(int index)
            {
                if (variantLabels != null && index >= 0 && index < variantLabels.Count
                    && !string.IsNullOrWhiteSpace(variantLabels[index]))
                    return variantLabels[index];
                return VariantId(index);
            }
        }

        /// <summary>One variant's contribution across every attribute, parallel to <see cref="attributes"/>.</summary>
        [Serializable]
        public class VariantStats
        {
            [Tooltip("Parallel to the set's Attributes list. Roughly 0-1 per entry; the UI " +
                     "sums them across segments and scales the total to a 0-99 readout.")]
            public List<float> values = new();
        }

        /// <summary>
        /// A named attribute the glove is scored on. These are the game-facing figures —
        /// protection, bond, agility — that shift as the player changes materials, which is
        /// what makes the screen read as equipment rather than a swatch picker.
        /// </summary>
        [Serializable]
        public class AttributeDef
        {
            public string label = "ATTRIBUTE";

            [Tooltip("Short line shown when this attribute leads the readout.")]
            public string blurb = "";

            [Tooltip("Bar colour. Leave black to fall back to the UI's segment accent.")]
            public Color color = Color.black;
        }

        public string assetName = "falcon_glove";

        [Tooltip("The attributes every variant is scored on, in display order.")]
        public List<AttributeDef> attributes = new();

        public List<Segment> segments = new();

        [Tooltip("One image per whole-glove design preset. Left empty, the design tiles fall " +
                 "back to the hero segment's part thumbnail, which shows a single piece " +
                 "rather than the finished outfit.")]
        public List<Texture2D> designThumbnails = new();

        /// <summary>Preview for a whole-outfit preset, or null if none has been supplied.</summary>
        public Texture2D DesignThumbnail(int index) =>
            (designThumbnails != null && index >= 0 && index < designThumbnails.Count)
                ? designThumbnails[index]
                : null;

        /// <summary>
        /// Totals one attribute across the current selection, returned 0-1.
        /// Divided by the segment count so the scale holds however many segments exist.
        /// </summary>
        public float TotalAttribute(int attribute, IReadOnlyList<int> selection)
        {
            if (segments.Count == 0 || selection == null) return 0f;

            float sum = 0f;
            int counted = 0;
            for (int s = 0; s < segments.Count && s < selection.Count; s++)
            {
                sum += segments[s].Stat(selection[s], attribute);
                counted++;
            }
            return counted == 0 ? 0f : Mathf.Clamp01(sum / counted);
        }

        public Segment FindSegment(string id) => segments.Find(s => s.id == id);

        /// <summary>Total number of distinct assemblies expressible by this set.</summary>
        public int CombinationCount
        {
            get
            {
                int total = 1;
                foreach (var s in segments)
                    total *= Mathf.Max(1, s.VariantCount);
                return total;
            }
        }
    }
}
